Update all non-major dependencies (#41)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@mui/lab](https://mui.com/material-ui/about-the-lab/)
([source](https://togithub.com/mui/material-ui)) | [`5.0.0-alpha.114` ->
`5.0.0-alpha.115`](https://renovatebot.com/diffs/npm/@mui%2flab/5.0.0-alpha.114/5.0.0-alpha.115)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.115/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.115/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.115/compatibility-slim/5.0.0-alpha.114)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.115/confidence-slim/5.0.0-alpha.114)](https://docs.renovatebot.com/merge-confidence/)
|
| [@mui/material](https://mui.com/material-ui/getting-started/overview/)
([source](https://togithub.com/mui/material-ui)) | [`5.11.3` ->
`5.11.4`](https://renovatebot.com/diffs/npm/@mui%2fmaterial/5.11.3/5.11.4)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.4/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.4/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.4/compatibility-slim/5.11.3)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.4/confidence-slim/5.11.3)](https://docs.renovatebot.com/merge-confidence/)
|
| [plotly.js](https://togithub.com/plotly/plotly.js) | [`2.17.0` ->
`2.17.1`](https://renovatebot.com/diffs/npm/plotly.js/2.17.0/2.17.1) |
[![age](https://badges.renovateapi.com/packages/npm/plotly.js/2.17.1/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/plotly.js/2.17.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/plotly.js/2.17.1/compatibility-slim/2.17.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/plotly.js/2.17.1/confidence-slim/2.17.0)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`2.8.2` ->
`2.8.3`](https://renovatebot.com/diffs/npm/prettier/2.8.2/2.8.3) |
[![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/compatibility-slim/2.8.2)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/confidence-slim/2.8.2)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>mui/material-ui (@&#8203;mui/lab)</summary>

###
[`v5.0.0-alpha.115`](https://togithub.com/mui/material-ui/compare/e9d8fa07e1ff979bcaf92837b131cd9e292f0161...bc859d95e4415f880cd6bcb6f44cc9e5e8c8097c)

[Compare
Source](https://togithub.com/mui/material-ui/compare/e9d8fa07e1ff979bcaf92837b131cd9e292f0161...bc859d95e4415f880cd6bcb6f44cc9e5e8c8097c)

</details>

<details>
<summary>mui/material-ui (@&#8203;mui/material)</summary>

###
[`v5.11.4`](https://togithub.com/mui/material-ui/blob/HEAD/CHANGELOG.md#&#8203;5114)

[Compare
Source](https://togithub.com/mui/material-ui/compare/v5.11.3...v5.11.4)

<!-- generated comparing v5.11.3..master -->

*Jan 9, 2023*

A big thanks to the 14 contributors who made this release possible.
This release was mostly about 🐛 bug fixes and 📚 documentation
improvements.

##### `@mui/material@5.11.4`

- \[Autocomplete] Add index to renderOption's
AutocompleteRenderOptionState
([#&#8203;35578](https://togithub.com/mui/material-ui/issues/35578))
[@&#8203;CowDotDev](https://togithub.com/CowDotDev)
- \[Autocomplete] Fix grammar in console.error in `useAutocomplete`
([#&#8203;35723](https://togithub.com/mui/material-ui/issues/35723))
[@&#8203;hamirmahal](https://togithub.com/hamirmahal)
- \[Modal] Fix can't override Backdrop Props using new Slots API
([#&#8203;35140](https://togithub.com/mui/material-ui/issues/35140))
[@&#8203;ZeeshanTamboli](https://togithub.com/ZeeshanTamboli)
- \[Select] Revert "Update `renderValue` prop's TypeScript type
([#&#8203;34177](https://togithub.com/mui/material-ui/issues/34177))"
([#&#8203;35733](https://togithub.com/mui/material-ui/issues/35733))
[@&#8203;michaldudak](https://togithub.com/michaldudak)
- \[Tabs] Throw error only if individual `Tab` is hidden, not the whole
`Tabs`
([#&#8203;34026](https://togithub.com/mui/material-ui/issues/34026))
[@&#8203;Ryczko](https://togithub.com/Ryczko)
- \[TextField] Improve WCAG 2.4.7 with error={true}
([#&#8203;35687](https://togithub.com/mui/material-ui/issues/35687))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[Tooltip] Remove `data-foo` attribute
([#&#8203;35736](https://togithub.com/mui/material-ui/issues/35736))
[@&#8203;koolskateguy89](https://togithub.com/koolskateguy89)

##### `@mui/joy@5.0.0-alpha.62`

- \[Autocomplete]\[joy] Specify `type` attribute for popup indicator
([#&#8203;35648](https://togithub.com/mui/material-ui/issues/35648))
[@&#8203;hbjORbj](https://togithub.com/hbjORbj)
- \[Joy] Miscellaneous improvements
([#&#8203;35769](https://togithub.com/mui/material-ui/issues/35769))
[@&#8203;siriwatknp](https://togithub.com/siriwatknp)
- \[Joy] Improve `onKeyDown` event handler for demo
([#&#8203;35642](https://togithub.com/mui/material-ui/issues/35642))
[@&#8203;hbjORbj](https://togithub.com/hbjORbj)

##### `@mui/base@5.0.0-alpha.113`

- \[Portal]\[base] Convert code to TypeScript
([#&#8203;35657](https://togithub.com/mui/material-ui/issues/35657))
[@&#8203;sai6855](https://togithub.com/sai6855)

##### Docs

- \[docs] Revise and expand Joy UI Button doc
([#&#8203;35737](https://togithub.com/mui/material-ui/issues/35737))
[@&#8203;samuelsycamore](https://togithub.com/samuelsycamore)
- \[docs] Document the workaround for crashing a translated page
([#&#8203;35720](https://togithub.com/mui/material-ui/issues/35720))
[@&#8203;michaldudak](https://togithub.com/michaldudak)
- \[docs] Fix API page for `MenuItem` to list all valid props
([#&#8203;35561](https://togithub.com/mui/material-ui/issues/35561))
[@&#8203;mnajdova](https://togithub.com/mnajdova)
- \[docs] Fix ad exception in Joy UI
([#&#8203;35685](https://togithub.com/mui/material-ui/issues/35685))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[docs] Fix content wider than screen regression
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[examples] Add `Vite.js with TypeScript` example
([#&#8203;35683](https://togithub.com/mui/material-ui/issues/35683))
[@&#8203;miha53cevic](https://togithub.com/miha53cevic)

##### Core

- \[core] Close 2022 developer survey
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[core] Fix the product license reference name
([#&#8203;35703](https://togithub.com/mui/material-ui/issues/35703))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[core] Use TypeScript AST instead of TTP for component doc building
([#&#8203;35379](https://togithub.com/mui/material-ui/issues/35379))
[@&#8203;flaviendelangle](https://togithub.com/flaviendelangle)
- \[test] Always use & for nesting styles
([#&#8203;35702](https://togithub.com/mui/material-ui/issues/35702))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[website] Improve Lead Designer role description
([#&#8203;35684](https://togithub.com/mui/material-ui/issues/35684))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)

All contributors of this release in alphabetical order:
[@&#8203;CowDotDev](https://togithub.com/CowDotDev),
[@&#8203;flaviendelangle](https://togithub.com/flaviendelangle),
[@&#8203;hamirmahal](https://togithub.com/hamirmahal),
[@&#8203;hbjORbj](https://togithub.com/hbjORbj),
[@&#8203;koolskateguy89](https://togithub.com/koolskateguy89),
[@&#8203;michaldudak](https://togithub.com/michaldudak),
[@&#8203;miha53cevic](https://togithub.com/miha53cevic),
[@&#8203;mnajdova](https://togithub.com/mnajdova),
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari),
[@&#8203;Ryczko](https://togithub.com/Ryczko),
[@&#8203;sai6855](https://togithub.com/sai6855),
[@&#8203;samuelsycamore](https://togithub.com/samuelsycamore),
[@&#8203;siriwatknp](https://togithub.com/siriwatknp),
[@&#8203;ZeeshanTamboli](https://togithub.com/ZeeshanTamboli)

</details>

<details>
<summary>plotly/plotly.js</summary>

###
[`v2.17.1`](https://togithub.com/plotly/plotly.js/blob/HEAD/CHANGELOG.md#&#8203;2171----2023-01-09)

[Compare
Source](https://togithub.com/plotly/plotly.js/compare/v2.17.0...v2.17.1)

##### Fixed

- Fix line redraw (regression introduced in 2.15.0)
\[[#&#8203;6429](https://togithub.com/plotly/plotly.js/pull/6429)]

</details>

<details>
<summary>prettier/prettier</summary>

###
[`v2.8.3`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;283)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.2...2.8.3)

[diff](https://togithub.com/prettier/prettier/compare/2.8.2...2.8.3)

##### Allow self-closing tags on custom elements
([#&#8203;14170](https://togithub.com/prettier/prettier/pull/14170) by
[@&#8203;fisker](https://togithub.com/fisker))

See [Angular v15.1.0 release
note](https://togithub.com/angular/angular/releases/tag/15.1.0) for
details.

<!-- prettier-ignore -->

```html
// Input
<app-test/>

// Prettier 2.8.2
SyntaxError: Only void and foreign elements can be self closed "app-test" (1:1)
> 1 | <app-test/>
    | ^^^^^^^^^
  2 |

// Prettier 2.8.3
<app-test />
```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on Saturday" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/rparini/cxroots-app).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNC4xMDAuMSIsInVwZGF0ZWRJblZlciI6IjM0LjEwMC4xIn0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>