Update all non-major dependencies (#50)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@mui/lab](https://mui.com/material-ui/about-the-lab/)
([source](https://togithub.com/mui/material-ui)) | [`5.0.0-alpha.122` ->
`5.0.0-alpha.124`](https://renovatebot.com/diffs/npm/@mui%2flab/5.0.0-alpha.122/5.0.0-alpha.124)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.124/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.124/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.124/compatibility-slim/5.0.0-alpha.122)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.124/confidence-slim/5.0.0-alpha.122)](https://docs.renovatebot.com/merge-confidence/)
|
| [@mui/material](https://mui.com/material-ui/getting-started/overview/)
([source](https://togithub.com/mui/material-ui)) | [`5.11.12` ->
`5.11.14`](https://renovatebot.com/diffs/npm/@mui%2fmaterial/5.11.12/5.11.14)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.14/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.14/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.14/compatibility-slim/5.11.12)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.11.14/confidence-slim/5.11.12)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/jest](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) |
[`29.4.0` ->
`29.5.0`](https://renovatebot.com/diffs/npm/@types%2fjest/29.4.0/29.5.0)
|
[![age](https://badges.renovateapi.com/packages/npm/@types%2fjest/29.5.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@types%2fjest/29.5.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@types%2fjest/29.5.0/compatibility-slim/29.4.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@types%2fjest/29.5.0/confidence-slim/29.4.0)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) |
[`18.0.28` ->
`18.0.29`](https://renovatebot.com/diffs/npm/@types%2freact/18.0.28/18.0.29)
|
[![age](https://badges.renovateapi.com/packages/npm/@types%2freact/18.0.29/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@types%2freact/18.0.29/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@types%2freact/18.0.29/compatibility-slim/18.0.28)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@types%2freact/18.0.29/confidence-slim/18.0.28)](https://docs.renovatebot.com/merge-confidence/)
|
| [jest-canvas-mock](https://togithub.com/hustcc/jest-canvas-mock) |
[`2.4.0` ->
`2.5.0`](https://renovatebot.com/diffs/npm/jest-canvas-mock/2.4.0/2.5.0)
|
[![age](https://badges.renovateapi.com/packages/npm/jest-canvas-mock/2.5.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/jest-canvas-mock/2.5.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/jest-canvas-mock/2.5.0/compatibility-slim/2.4.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/jest-canvas-mock/2.5.0/confidence-slim/2.4.0)](https://docs.renovatebot.com/merge-confidence/)
|
| [mathjs](https://mathjs.org)
([source](https://togithub.com/josdejong/mathjs)) | [`11.6.0` ->
`11.7.0`](https://renovatebot.com/diffs/npm/mathjs/11.6.0/11.7.0) |
[![age](https://badges.renovateapi.com/packages/npm/mathjs/11.7.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/mathjs/11.7.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/mathjs/11.7.0/compatibility-slim/11.6.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/mathjs/11.7.0/confidence-slim/11.6.0)](https://docs.renovatebot.com/merge-confidence/)
|
| [plotly.js](https://togithub.com/plotly/plotly.js) | [`2.18.2` ->
`2.20.0`](https://renovatebot.com/diffs/npm/plotly.js/2.18.2/2.20.0) |
[![age](https://badges.renovateapi.com/packages/npm/plotly.js/2.20.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/plotly.js/2.20.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/plotly.js/2.20.0/compatibility-slim/2.18.2)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/plotly.js/2.20.0/confidence-slim/2.18.2)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`2.8.4` ->
`2.8.7`](https://renovatebot.com/diffs/npm/prettier/2.8.4/2.8.7) |
[![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/compatibility-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/confidence-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>mui/material-ui</summary>

###
[`v5.0.0-alpha.124`](https://togithub.com/mui/material-ui/blob/HEAD/CHANGELOG.md#muilab500-alpha124)

[Compare
Source](https://togithub.com/mui/material-ui/compare/9f7a2bfac55faed1b1c6c7b4b6d1b1659a076bab...f34d17c3294fcdb63fe9a135b4f3aa2459c81189)

- \[Masonry] Include Masonry in theme augmentation interface
([#&#8203;36533](https://togithub.com/mui/material-ui/issues/36533))
[@&#8203;hbjORbj](https://togithub.com/hbjORbj)

###
[`v5.0.0-alpha.123`](https://togithub.com/mui/material-ui/compare/b76b8f1098a6c01f39e5e19bf3abf77c2b9cf475...9f7a2bfac55faed1b1c6c7b4b6d1b1659a076bab)

[Compare
Source](https://togithub.com/mui/material-ui/compare/b76b8f1098a6c01f39e5e19bf3abf77c2b9cf475...9f7a2bfac55faed1b1c6c7b4b6d1b1659a076bab)

</details>

<details>
<summary>hustcc/jest-canvas-mock</summary>

###
[`v2.5.0`](https://togithub.com/hustcc/jest-canvas-mock/blob/HEAD/CHANGELOG.md#Version-250)

[Compare
Source](https://togithub.com/hustcc/jest-canvas-mock/compare/v2.4.0...v2.5.0)

- feat: export a function to re-initialize mocks
([#&#8203;98](https://togithub.com/hustcc/jest-canvas-mock/issues/98))
- docs: fix some typos
([#&#8203;104](https://togithub.com/hustcc/jest-canvas-mock/issues/104))
- fix: copy & paste mistake: toBlob -> toDataURL
([#&#8203;101](https://togithub.com/hustcc/jest-canvas-mock/issues/101))
- chore: add Contributors LitoMore
([#&#8203;94](https://togithub.com/hustcc/jest-canvas-mock/issues/94))

</details>

<details>
<summary>josdejong/mathjs</summary>

###
[`v11.7.0`](https://togithub.com/josdejong/mathjs/blob/HEAD/HISTORY.md#unpublished-changes-since-1170)

[Compare
Source](https://togithub.com/josdejong/mathjs/compare/v11.6.0...v11.7.0)

- Implemented aliases `amp` and `amps` for unit `ampere`
([#&#8203;2917](https://togithub.com/josdejong/mathjs/issues/2917)).
    Thanks [@&#8203;veggiesaurus](https://togithub.com/veggiesaurus).

</details>

<details>
<summary>plotly/plotly.js</summary>

###
[`v2.20.0`](https://togithub.com/plotly/plotly.js/blob/HEAD/CHANGELOG.md#&#8203;2200----2023-03-15)

[Compare
Source](https://togithub.com/plotly/plotly.js/compare/v2.19.1...v2.20.0)

##### Added

- Add `title.automargin` to enable automatic top and bottom margining
for both container and paper referenced titles
\[[#&#8203;6428](https://togithub.com/plotly/plotly.js/pull/6428)],
with thanks to [Gamma Technologies](https://www.gtisoft.com/) for
sponsoring the related development.

###
[`v2.19.1`](https://togithub.com/plotly/plotly.js/blob/HEAD/CHANGELOG.md#&#8203;2191----2023-03-14)

[Compare
Source](https://togithub.com/plotly/plotly.js/compare/v2.19.0...v2.19.1)

##### Fixed

- Ensure slider range stays in bounds during the drag
\[[#&#8203;4448](https://togithub.com/plotly/plotly.js/pull/4448)],
with thanks to [@&#8203;jay-bis](https://togithub.com/jay-bis) for the
contribution!

###
[`v2.19.0`](https://togithub.com/plotly/plotly.js/blob/HEAD/CHANGELOG.md#&#8203;2190----2023-03-13)

[Compare
Source](https://togithub.com/plotly/plotly.js/compare/v2.18.2...v2.19.0)

##### Added

- Add `label` attribute to shapes
\[[#&#8203;6454](https://togithub.com/plotly/plotly.js/pull/6454)],
with thanks to the [Volkswagen](https://www.volkswagenag.com) Center of
Excellence for Battery Systems for sponsoring development!
- Add `labelalias` to various axes namely cartesian, gl3d, polar, smith,
ternary, carpet,
indicator and colorbar
\[[#&#8203;6481](https://togithub.com/plotly/plotly.js/pull/6481)],
    this feature was anonymously sponsored: thank you to our sponsor!

##### Changed

- Upgrade `is-mobile` dependency
\[[#&#8203;6517](https://togithub.com/plotly/plotly.js/pull/6517)]

##### Fixed

- Avoid overlap of point and axis hover labels for `hovermode: 'x'|'y'`
\[[#&#8203;6442](https://togithub.com/plotly/plotly.js/pull/6442)],
with thanks to [@&#8203;dagroe](https://togithub.com/dagroe) for the
contribution!

</details>

<details>
<summary>prettier/prettier</summary>

###
[`v2.8.7`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;287)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

[diff](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

##### Allow multiple decorators on same getter/setter
([#&#8203;14584](https://togithub.com/prettier/prettier/pull/14584) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```ts
// Input
class A {
  @&#8203;decorator()
  get foo () {}
  
  @&#8203;decorator()
  set foo (value) {}
}

// Prettier 2.8.6
SyntaxError: Decorators cannot be applied to multiple get/set accessors of the same name. (5:3)
  3 |   get foo () {}
  4 |   
> 5 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  6 |   set foo (value) {}
  7 | }

// Prettier 2.8.7
class A {
  @&#8203;decorator()
  get foo() {}

  @&#8203;decorator()
  set foo(value) {}
}
```

###
[`v2.8.6`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;286)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

[diff](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

##### Allow decorators on private members and class expressions
([#&#8203;14548](https://togithub.com/prettier/prettier/pull/14548) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```ts
// Input
class A {
  @&#8203;decorator()
  #privateMethod () {}
}

// Prettier 2.8.5
SyntaxError: Decorators are not valid here. (2:3)
  1 | class A {
> 2 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  3 |   #privateMethod () {}
  4 | }

// Prettier 2.8.6
class A {
  @&#8203;decorator()
  #privateMethod() {}
}
```

###
[`v2.8.5`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;285)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

[diff](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

##### Support TypeScript 5.0
([#&#8203;14391](https://togithub.com/prettier/prettier/pull/14391) by
[@&#8203;fisker](https://togithub.com/fisker),
[#&#8203;13819](https://togithub.com/prettier/prettier/pull/13819) by
[@&#8203;fisker](https://togithub.com/fisker),
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

TypeScript 5.0 introduces two new syntactic features:

-   `const` modifiers for type parameters
-   `export type *` declarations

##### Add missing parentheses for decorator
([#&#8203;14393](https://togithub.com/prettier/prettier/pull/14393) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}

// Prettier 2.8.4
class Person {
  @&#8203;myDecoratorArray[0]
  greet() {}
}

// Prettier 2.8.5
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}
```

##### Add parentheses for `TypeofTypeAnnotation` to improve readability
([#&#8203;14458](https://togithub.com/prettier/prettier/pull/14458) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
type A = (typeof node.children)[];

// Prettier 2.8.4
type A = typeof node.children[];

// Prettier 2.8.5
type A = (typeof node.children)[];
```

##### Support `max_line_length=off` when parsing `.editorconfig`
([#&#8203;14516](https://togithub.com/prettier/prettier/pull/14516) by
[@&#8203;josephfrazier](https://togithub.com/josephfrazier))

If an .editorconfig file is in your project and it sets
`max_line_length=off` for the file you're formatting,
it will be interpreted as a `printWidth` of `Infinity` rather than being
ignored
(which previously resulted in the default `printWidth` of 80 being
applied, if not overridden by Prettier-specific configuration).

<!-- prettier-ignore -->

```html
<!-- Input -->
<div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}/>

<!-- Prettier 2.8.4 -->
<div
  className="HelloWorld"
  title={`You are visitor number ${num}`}
  onMouseOver={onMouseOver}
/>;

<!-- Prettier 2.8.5 -->
<div className="HelloWorld" title={`You are visitor number ${num}`} onMouseOver={onMouseOver} />;
```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on Saturday" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/rparini/cxroots-app).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNS4xNC4yIiwidXBkYXRlZEluVmVyIjoiMzUuMTQuMiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>