Update all non-major dependencies (#19)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@mui/lab](https://mui.com/material-ui/about-the-lab/)
([source](https://togithub.com/mui/material-ui)) | [`5.0.0-alpha.99` ->
`5.0.0-alpha.100`](https://renovatebot.com/diffs/npm/@mui%2flab/5.0.0-alpha.99/5.0.0-alpha.100)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.100/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.100/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.100/compatibility-slim/5.0.0-alpha.99)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2flab/5.0.0-alpha.100/confidence-slim/5.0.0-alpha.99)](https://docs.renovatebot.com/merge-confidence/)
|
| [@mui/material](https://mui.com/material-ui/getting-started/overview/)
([source](https://togithub.com/mui/material-ui)) | [`5.10.5` ->
`5.10.6`](https://renovatebot.com/diffs/npm/@mui%2fmaterial/5.10.5/5.10.6)
|
[![age](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.10.6/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.10.6/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.10.6/compatibility-slim/5.10.5)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@mui%2fmaterial/5.10.6/confidence-slim/5.10.5)](https://docs.renovatebot.com/merge-confidence/)
|
| [katex](https://katex.org)
([source](https://togithub.com/KaTeX/KaTeX)) | [`0.15.6` ->
`0.16.2`](https://renovatebot.com/diffs/npm/katex/0.15.6/0.16.2) |
[![age](https://badges.renovateapi.com/packages/npm/katex/0.16.2/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/katex/0.16.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/katex/0.16.2/compatibility-slim/0.15.6)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/katex/0.16.2/confidence-slim/0.15.6)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`2.4.1` ->
`2.7.1`](https://renovatebot.com/diffs/npm/prettier/2.4.1/2.7.1) |
[![age](https://badges.renovateapi.com/packages/npm/prettier/2.7.1/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.7.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/prettier/2.7.1/compatibility-slim/2.4.1)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.7.1/confidence-slim/2.4.1)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>mui/material-ui (@&#8203;mui/lab)</summary>

###
[`v5.0.0-alpha.100`](https://togithub.com/mui/material-ui/compare/594d87dab0e43e641a6826c935df8f2c10672955...0f75f3d78b67c405c23bfd14a29aedff367415b7)

[Compare
Source](https://togithub.com/mui/material-ui/compare/594d87dab0e43e641a6826c935df8f2c10672955...0f75f3d78b67c405c23bfd14a29aedff367415b7)

</details>

<details>
<summary>mui/material-ui (@&#8203;mui/material)</summary>

###
[`v5.10.6`](https://togithub.com/mui/material-ui/blob/HEAD/CHANGELOG.md#&#8203;5106)

[Compare
Source](https://togithub.com/mui/material-ui/compare/v5.10.5...v5.10.6)

<!-- generated comparing v5.10.5..master -->

*Sep 19, 2022*

A big thanks to the 11 contributors who made this release possible.
This release was mostly about 🐛 bug fixes and 📚 documentation
improvements.

##### `@mui/material@5.10.6`

- \[TextField] Fix conflict with `Bootstrap` even when label is not
defined
([#&#8203;34343](https://togithub.com/mui/material-ui/issues/34343))
[@&#8203;ZeeshanTamboli](https://togithub.com/ZeeshanTamboli)

##### `@mui/joy@5.0.0-alpha.46`

##### Breaking changes

- \[button]\[joy] Replace `start/endIcon` prop with `start/endDecorator`
([#&#8203;34288](https://togithub.com/mui/material-ui/issues/34288))
[@&#8203;hbjORbj](https://togithub.com/hbjORbj)

**BREAKING CHANGE**: replace `start/endIcon` with `start/endDecorator`.

    ```jsx
    // before
    <Button startIcon={...} endIcon={...} />

    // after
    <Button startDecorator={...} endDecorator={...} />
    ```

##### Changes

- \[Joy] Adjust the `Input` and `Textarea` styles
([#&#8203;34281](https://togithub.com/mui/material-ui/issues/34281))
[@&#8203;siriwatknp](https://togithub.com/siriwatknp)
- \[menu]\[joy] Set disablePortal default to false
([#&#8203;34283](https://togithub.com/mui/material-ui/issues/34283))
[@&#8203;tomasz-sodzawiczny](https://togithub.com/tomasz-sodzawiczny)

##### `@mui/base@5.0.0-alpha.98`

##### Breaking changes

- \[Select]\[base] Add event parameter to the onChange callback
([#&#8203;34158](https://togithub.com/mui/material-ui/issues/34158))
[@&#8203;michaldudak](https://togithub.com/michaldudak)

The SelectUnstyled and MultiSelectUnstyled `onChange` callbacks did not
have event as the first parameter, leading to inconsistency with other
components and native HTML elements.
This PR adds the event parameter as the first one and moves the newly
selected value to the second position. Because of this, it's a breaking
change.
    This also affects Select from Joy UI.

    ```jsx
    // before
    <SelectUnstyled onChange={(newValue) => { /* ... */ }} />

    // after
    <SelectUnstyled onChange={(event, newValue) => { /* ... */ }} />
    ```

##### Docs

- \[blog] The Date Pickers gets a stable v5 release
([#&#8203;34152](https://togithub.com/mui/material-ui/issues/34152))
[@&#8203;alexfauquette](https://togithub.com/alexfauquette)
- \[blog] Improve image handling
([#&#8203;34222](https://togithub.com/mui/material-ui/issues/34222))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[blog] Correct 2021 survey data interpretation
([#&#8203;34291](https://togithub.com/mui/material-ui/issues/34291))
[@&#8203;samuelsycamore](https://togithub.com/samuelsycamore)
- \[docs] Remove expired AospExtended showcase
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[docs] Link the OpenSSF Best Practices card
([#&#8203;34331](https://togithub.com/mui/material-ui/issues/34331))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[docs] Fix 301 link to external projects
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[docs] Move 12 component names to Title Case
([#&#8203;34188](https://togithub.com/mui/material-ui/issues/34188))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[docs] Fix broken links
([#&#8203;34320](https://togithub.com/mui/material-ui/issues/34320))
[@&#8203;alexfauquette](https://togithub.com/alexfauquette)
- \[docs] Add notification for MUI Base announcement post
([#&#8203;34295](https://togithub.com/mui/material-ui/issues/34295))
[@&#8203;samuelsycamore](https://togithub.com/samuelsycamore)
- \[website] Fix MUI X subscribe email border style
([#&#8203;34330](https://togithub.com/mui/material-ui/issues/34330))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[website] Improve security header
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)

##### Core

- \[core] Lock file maintenance
([#&#8203;34161](https://togithub.com/mui/material-ui/issues/34161))
[@&#8203;renovate](https://togithub.com/renovate)\[bot]
- \[core] Issue template: move reproduction steps to the top
([#&#8203;34279](https://togithub.com/mui/material-ui/issues/34279))
[@&#8203;Janpot](https://togithub.com/Janpot)
- \[core] Create shared Next.js baseline config
([#&#8203;34259](https://togithub.com/mui/material-ui/issues/34259))
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari)
- \[core] In `typescript-to-proptypes`, respect the value pass to the
generic
([#&#8203;34311](https://togithub.com/mui/material-ui/issues/34311))
[@&#8203;flaviendelangle](https://togithub.com/flaviendelangle)

All contributors of this release in alphabetical order:
[@&#8203;alexfauquette](https://togithub.com/alexfauquette),
[@&#8203;flaviendelangle](https://togithub.com/flaviendelangle),
[@&#8203;hbjORbj](https://togithub.com/hbjORbj),
[@&#8203;Janpot](https://togithub.com/Janpot),
[@&#8203;michaldudak](https://togithub.com/michaldudak),
[@&#8203;oliviertassinari](https://togithub.com/oliviertassinari),
[@&#8203;renovate](https://togithub.com/renovate)\[bot],
[@&#8203;samuelsycamore](https://togithub.com/samuelsycamore),
[@&#8203;siriwatknp](https://togithub.com/siriwatknp),
[@&#8203;tomasz-sodzawiczny](https://togithub.com/tomasz-sodzawiczny),
[@&#8203;ZeeshanTamboli](https://togithub.com/ZeeshanTamboli)

</details>

<details>
<summary>KaTeX/KaTeX</summary>

###
[`v0.16.2`](https://togithub.com/KaTeX/KaTeX/blob/HEAD/CHANGELOG.md#&#8203;0162-httpsgithubcomKaTeXKaTeXcomparev0161v0162-2022-08-29)

[Compare
Source](https://togithub.com/KaTeX/KaTeX/compare/v0.16.1...v0.16.2)

##### Bug Fixes

- **auto-render:** concatenate content of successive text nodes
([#&#8203;3422](https://togithub.com/KaTeX/KaTeX/issues/3422))
([4d3fdd8](https://togithub.com/KaTeX/KaTeX/commit/4d3fdd8647a1c320dc7bcb9c9ea2af81379f700d))
- Implement \pmb via CSS text-shadow
([#&#8203;3505](https://togithub.com/KaTeX/KaTeX/issues/3505))
([176552a](https://togithub.com/KaTeX/KaTeX/commit/176552a69183d71425b491d4cc2fa1d462a1246a))

###
[`v0.16.1`](https://togithub.com/KaTeX/KaTeX/blob/HEAD/CHANGELOG.md#&#8203;0161-httpsgithubcomKaTeXKaTeXcomparev0160v0161-2022-08-28)

[Compare
Source](https://togithub.com/KaTeX/KaTeX/compare/v0.16.0...v0.16.1)

##### Bug Fixes

- Use SVGs for some stacked delims
([#&#8203;3686](https://togithub.com/KaTeX/KaTeX/issues/3686))
([8a65a2e](https://togithub.com/KaTeX/KaTeX/commit/8a65a2e1fd69ffeee2fac62229f9f05ebf6afd45))

###
[`v0.16.0`](https://togithub.com/KaTeX/KaTeX/blob/HEAD/CHANGELOG.md#&#8203;0160-httpsgithubcomKaTeXKaTeXcomparev0156v0160-2022-06-06)

[Compare
Source](https://togithub.com/KaTeX/KaTeX/compare/v0.15.6...v0.16.0)

##### Bug Fixes

- **copy-tex:** Use JS (instead of CSS) to select full equation, solving
display glitches
([#&#8203;3586](https://togithub.com/KaTeX/KaTeX/issues/3586))
([8c2d852](https://togithub.com/KaTeX/KaTeX/commit/8c2d852c4af213ba4e2f4a3b875498c367e9a119))

##### BREAKING CHANGES

- **copy-tex:** copy-tex extension no longer has (or requires) a CSS
file.

####
[0.15.6](https://togithub.com/KaTeX/KaTeX/compare/v0.15.5...v0.15.6)
(2022-05-20)

##### Features

- Support \Braket, \set, and \Set
([#&#8203;3214](https://togithub.com/KaTeX/KaTeX/issues/3214))
([9e3ae4d](https://togithub.com/KaTeX/KaTeX/commit/9e3ae4d5a81b825b90a055b46d5c7ab0a3a50379))

####
[0.15.5](https://togithub.com/KaTeX/KaTeX/compare/v0.15.4...v0.15.5)
(2022-05-20)

##### Bug Fixes

- Avoid crash when \ce{} is empty
([#&#8203;3627](https://togithub.com/KaTeX/KaTeX/issues/3627))
([4865e45](https://togithub.com/KaTeX/KaTeX/commit/4865e4543774441467f81f81ef45c9b59f1349ae))

####
[0.15.4](https://togithub.com/KaTeX/KaTeX/compare/v0.15.3...v0.15.4)
(2022-05-20)

##### Features

- Support Unicode (sub|super)script characters
([#&#8203;3633](https://togithub.com/KaTeX/KaTeX/issues/3633))
([d8fc35e](https://togithub.com/KaTeX/KaTeX/commit/d8fc35e6a97f8e561c723b93ad275cf5a7f3094a))

####
[0.15.3](https://togithub.com/KaTeX/KaTeX/compare/v0.15.2...v0.15.3)
(2022-03-13)

##### Bug Fixes

- Apply operator spacing to Unicode ∙ ∘ ∖
([#&#8203;3584](https://togithub.com/KaTeX/KaTeX/issues/3584))
([b362fc0](https://togithub.com/KaTeX/KaTeX/commit/b362fc0b3941926a7a752cab34af6e29570c669a))

####
[0.15.2](https://togithub.com/KaTeX/KaTeX/compare/v0.15.1...v0.15.2)
(2022-01-12)

##### Bug Fixes

- \mathinner MathML when invoked as a denominator.
([#&#8203;3501](https://togithub.com/KaTeX/KaTeX/issues/3501))
([1f85125](https://togithub.com/KaTeX/KaTeX/commit/1f8512577b58962db2615175121ac9636245f596)),
closes [#&#8203;3500](https://togithub.com/KaTeX/KaTeX/issues/3500)

####
[0.15.1](https://togithub.com/KaTeX/KaTeX/compare/v0.15.0...v0.15.1)
(2021-10-31)

##### Features

- \nonumber/\notag support, \tag per row of {align}
([#&#8203;2952](https://togithub.com/KaTeX/KaTeX/issues/2952))
([52c4778](https://togithub.com/KaTeX/KaTeX/commit/52c4778b156110c0b2bdd3d7a3b81bbf76d21800)),
closes [#&#8203;2950](https://togithub.com/KaTeX/KaTeX/issues/2950)
[#&#8203;2379](https://togithub.com/KaTeX/KaTeX/issues/2379)

</details>

<details>
<summary>prettier/prettier</summary>

###
[`v2.7.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;271)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.7.0...2.7.1)

[diff](https://togithub.com/prettier/prettier/compare/2.7.0...2.7.1)

##### Keep useful empty lines in description
([#&#8203;13013](https://togithub.com/prettier/prettier/pull/13013) by
[@&#8203;chimurai](https://togithub.com/chimurai))

<!-- prettier-ignore -->

```graphql
```

###
[`v2.7.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#Prettier-270)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.6.2...2.7.0)

"""
First line
Second Line
"""
type Person {
name: String
}

###
[`v2.6.2`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;262)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.6.1...2.6.2)

[diff](https://togithub.com/prettier/prettier/compare/2.6.1...2.6.2)

##### Fix LESS/SCSS format error
([#&#8203;12536](https://togithub.com/prettier/prettier/pull/12536) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```less
// Input
.background-gradient(@&#8203;cut) {
    background: linear-gradient(
        to right,
        @&#8203;white 0%,
        @&#8203;white (@&#8203;cut - 0.01%),
        @&#8203;portal-background @&#8203;cut,
        @&#8203;portal-background 100%
    );
}

// Prettier 2.6.1
TypeError: Cannot read properties of undefined (reading 'endOffset')

// Prettier 2.6.2
.background-gradient(@&#8203;cut) {
  background: linear-gradient(
    to right,
    @&#8203;white 0%,
    @&#8203;white (@&#8203;cut - 0.01%),
    @&#8203;portal-background @&#8203;cut,
    @&#8203;portal-background 100%
  );
}
```

##### Update `meriyah` to fix several bugs
([#&#8203;12567](https://togithub.com/prettier/prettier/pull/12567) by
[@&#8203;fisker](https://togithub.com/fisker), fixes in
[`meriyah`](https://togithub.com/meriyah/meriyah/) by
[@&#8203;3cp](https://togithub.com/3cp))

Fixes bugs when parsing following valid code:

```js
foo(await bar());
```

```js
const regex = /.*/ms;
```

```js
const element = <p>{/w/.test(s)}</p>;
```

```js
class A extends B {
  #privateMethod() {
    super.method();
  }
}
```

###
[`v2.6.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;261)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.6.0...2.6.1)

[diff](https://togithub.com/prettier/prettier/compare/2.6.0...2.6.1)

##### Ignore `loglevel` when printing information
([#&#8203;12477](https://togithub.com/prettier/prettier/pull/12477) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```bash
```

###
[`v2.6.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#Prettier-260)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.5.1...2.6.0)

prettier --loglevel silent --find-config-path index.js

###
[`v2.5.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;251)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.5.0...2.5.1)

[diff](https://togithub.com/prettier/prettier/compare/2.5.0...2.5.1)

##### Improve formatting for empty tuple types
([#&#8203;11884](https://togithub.com/prettier/prettier/pull/11884) by
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```tsx
// Input
type Foo =
  Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends []
    ? Foo3
    : Foo4;

// Prettier 2.5.0
type Foo = Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends [

]
  ? Foo3
  : Foo4;

// Prettier 2.5.0 (tailingCommma = all)
// Invalid TypeScript code
type Foo = Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends [
  ,
]
  ? Foo3
  : Foo4;

// Prettier 2.5.1
type Foo =
  Foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo extends []
    ? Foo3
    : Foo4;

```

##### Fix compatibility with Jest inline snapshot test
([#&#8203;11892](https://togithub.com/prettier/prettier/pull/11892) by
[@&#8203;fisker](https://togithub.com/fisker))

A internal change in Prettier@v2.5.0 accidentally breaks the Jest inline
snapshot test.

##### Support Glimmer's named blocks
([#&#8203;11899](https://togithub.com/prettier/prettier/pull/11899) by
[@&#8203;duailibe](https://togithub.com/duailibe))

Prettier already supported this feature, but it converted empty named
blocks to self-closing, which is not supported by the Glimmer compiler.

See: [Glimmer's named
blocks](https://emberjs.github.io/rfcs/0460-yieldable-named-blocks.html).

<!-- prettier-ignore -->

```hbs
// Input
<Component>
  <:named></:named>
</Component>

// Prettier 2.5.0
<Component>
  <:named />
</Component>

// Prettier 2.5.1
<Component>
  <:named></:named>
</Component>
```

###
[`v2.5.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;250)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.4.1...2.5.0)

[diff](https://togithub.com/prettier/prettier/compare/2.4.1...2.5.0)

🔗 [Release Notes](https://prettier.io/blog/2021/11/25/2.5.0.html)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on Saturday" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click
this checkbox.

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/rparini/cxroots-app).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzMi4xOTUuNSIsInVwZGF0ZWRJblZlciI6IjMyLjE5OC4xIn0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>